import { describe, expect, it } from "vitest";
import { renderModule } from "../src/render.js";
import { datamodel, enumField, enumValues, field, model, options } from "./_fixtures.js";

/**
 * These tests focus on the *unusual* shapes a real-world Prisma schema
 * can throw at us. They live separately from mapper.test.ts so that
 * the long, fiddly cases don't drown out the simple ones.
 */

describe("edge cases: extreme field names", () => {
  it("handles field names that are pure numbers", () => {
    const m = model("X", [field("123", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain('"123": Schema.String,');
  });

  it("handles field names with leading underscores", () => {
    const m = model("X", [field("_private", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("_private: Schema.String,");
  });

  it("handles field names with $ characters", () => {
    const m = model("X", [field("$ref", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("$ref: Schema.String,");
  });

  it("handles emoji in field names (uncommon but allowed by Prisma)", () => {
    const m = model("X", [field("emoji-\u{1F600}", "String")]);
    const out = renderModule(datamodel([m]), options());
    // Should be quoted because of the hyphen
    expect(out).toContain('"emoji-\u{1F600}": Schema.String,');
  });

  it("handles very long field names", () => {
    const longName = "a".repeat(200);
    const m = model("X", [field(longName, "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain(`${longName}: Schema.String,`);
  });

  it("handles field names with unicode letters", () => {
    const m = model("X", [field("caf\u00e9", "String")]);
    const out = renderModule(datamodel([m]), options());
    // Unicode letters are valid identifier characters, so unquoted is fine
    expect(out).toContain("caf\u00e9: Schema.String,");
  });
});

describe("edge cases: model names", () => {
  it("handles a model named exactly like a reserved word", () => {
    const m = model("default", [field("y", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("export const defaultSchema = Schema.Struct({");
  });

  it("handles a model named with hyphens (quoted as default schema name)", () => {
    // Actually, Prisma wouldn't allow hyphens in model names. But our
    // emitter would just emit "bad-nameSchema" which TypeScript would
    // reject. We don't pre-validate model names -- the user is expected
    // to keep them valid identifiers.
    const m = model("valid", [field("y", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("export const validSchema = Schema.Struct({");
  });
});

describe("edge cases: model shapes", () => {
  it("handles a model with a single required field", () => {
    const m = model("X", [field("only", "String")]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toMatchInlineSnapshot(`
      "// AUTO-GENERATED by prisma-effect-schema-generator -- do not edit.
      // Regenerate via \`prisma generate\`.

      import { Schema } from \"effect\"

      export const XSchema = Schema.Struct({
        only: Schema.String,
      })

      export type ModelName =
        | \"X\"

      export const ALL_MODEL_NAMES = [\"X\"] as const
      "
    `);
  });

  it("handles a model with only optional fields", () => {
    const m = model("X", [
      field("a", "String", { isRequired: false }),
      field("b", "Int", { isRequired: false }),
    ]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("a: Schema.NullOr(Schema.String),");
    expect(out).toContain("b: Schema.NullOr(Schema.Number),");
  });

  it("handles a model with no fields", () => {
    const m = model("Empty", []);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("export const EmptySchema = Schema.Struct({");
    expect(out).toContain("})");
  });

  it("handles a model whose only fields are relations (all skipped)", () => {
    const m = model("Junction", [
      { kind: "object", name: "a", type: "A", isRequired: true, isList: false },
      { kind: "object", name: "b", type: "B", isRequired: true, isList: false },
    ]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("export const JunctionSchema = Schema.Struct({");
    expect(out).toContain("})");
    expect(out).not.toContain("a:");
    expect(out).not.toContain("b:");
  });

  it("handles a model with @map'd columns (we still emit the JS field name)", () => {
    const m = model("User", [
      {
        kind: "scalar",
        name: "createdAt",
        type: "DateTime",
        isRequired: true,
        isList: false,
        dbName: "created_at",
      },
    ]);
    const out = renderModule(datamodel([m]), options());
    // We always emit the Prisma field name, not the DB column name.
    expect(out).toContain("createdAt: Schema.DateFromSelf,");
    expect(out).not.toContain("created_at");
  });
});

describe("edge cases: many models and fields", () => {
  it("handles dozens of models in one go", () => {
    const models = Array.from({ length: 50 }, (_, i) =>
      model(`M${i.toString().padStart(2, "0")}`, [
        field("id", "String", { isId: true }),
        field("v", "Int"),
      ]),
    );
    const out = renderModule(datamodel(models), options());
    expect(out).toContain("export const M00Schema");
    expect(out).toContain("export const M49Schema");
    // All exported in ALL_MODEL_NAMES
    expect(out.match(/export const ALL_MODEL_NAMES/g)?.length).toBe(1);
    expect(out).toContain('"M00"');
    expect(out).toContain('"M49"');
  });

  it("handles a single model with many fields", () => {
    const fields = Array.from({ length: 50 }, (_, i) =>
      field(`f${i}`, i % 2 === 0 ? "String" : "Int"),
    );
    const m = model("Wide", fields);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("f0: Schema.String,");
    expect(out).toContain("f49: Schema.Number,");
  });
});

describe("edge cases: enum values", () => {
  it("handles enum values with special characters", () => {
    const m = model("X", [enumField("color", "Color")]);
    const d = datamodel(
      [m],
      [{ name: "Color", values: enumValues("RED", "BLUE", "WITH-DASH", "with space") }],
    );
    const out = renderModule(d, options());
    expect(out).toContain('Schema.Literal("RED")');
    expect(out).toContain('Schema.Literal("WITH-DASH")');
    expect(out).toContain('Schema.Literal("with space")');
  });

  it("handles enum values with quotes", () => {
    const m = model("X", [enumField("color", "Color")]);
    const d = datamodel([m], [{ name: "Color", values: enumValues('with"quote') }]);
    const out = renderModule(d, options());
    expect(out).toContain('Schema.Literal("with\\"quote")');
  });

  it("handles enum values with backslashes", () => {
    const m = model("X", [enumField("color", "Color")]);
    const d = datamodel([m], [{ name: "Color", values: enumValues("a\\b") }]);
    const out = renderModule(d, options());
    expect(out).toContain('Schema.Literal("a\\\\b")');
  });

  it("handles a single-value enum", () => {
    const m = model("X", [enumField("only", "Only")]);
    const d = datamodel([m], [{ name: "Only", values: enumValues("ONE") }]);
    const out = renderModule(d, options());
    expect(out).toContain('only: Schema.Literal("ONE")');
    expect(out).not.toContain("Schema.Union");
  });

  it("handles a hundred enum values", () => {
    const values = Array.from({ length: 100 }, (_, i) => `V${i}`);
    const m = model("X", [enumField("e", "E")]);
    const d = datamodel([m], [{ name: "E", values: enumValues(...values) }]);
    const out = renderModule(d, options());
    expect(out).toContain('Schema.Literal("V0")');
    expect(out).toContain('Schema.Literal("V99")');
    expect((out.match(/Schema\.Literal\("V\d+"\)/g) ?? []).length).toBe(100);
  });
});

describe("edge cases: list combinations", () => {
  it("renders all combinations of list + optional + types", () => {
    const m = model("All", [
      field("rs", "String", { isList: true, isRequired: true }),
      field("os", "String", { isList: false, isRequired: false }),
      field("rl", "Int", { isList: true, isRequired: true }),
      field("ol", "Int", { isList: false, isRequired: false }),
      field("rsl", "Boolean", { isList: true, isRequired: true }),
      field("osl", "DateTime", { isList: false, isRequired: false }),
    ]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("rs: Schema.Array(Schema.String),");
    expect(out).toContain("os: Schema.NullOr(Schema.String),");
    expect(out).toContain("rl: Schema.Array(Schema.Number),");
    expect(out).toContain("ol: Schema.NullOr(Schema.Number),");
    expect(out).toContain("rsl: Schema.Array(Schema.Boolean),");
    expect(out).toContain("osl: Schema.NullOr(Schema.DateFromSelf),");
  });
});

describe("edge cases: relation vs scalar mix", () => {
  it("correctly interleaves relation fields among scalars (relations skipped)", () => {
    const m = model("Post", [
      field("id", "String", { isId: true }),
      { kind: "object", name: "author", type: "User", isRequired: true, isList: false },
      field("title", "String"),
      {
        kind: "object",
        name: "comments",
        type: "Comment",
        isRequired: true,
        isList: true,
      },
      field("body", "String", { isRequired: false }),
    ]);
    const out = renderModule(datamodel([m]), options());
    expect(out).toContain("id: Schema.String,");
    expect(out).toContain("title: Schema.String,");
    expect(out).toContain("body: Schema.NullOr(Schema.String),");
    expect(out).not.toContain("author:");
    expect(out).not.toContain("comments:");
  });
});

describe("edge cases: re-imports under custom names", () => {
  it("uses the custom name in struct calls, literals, and unions", () => {
    const m = model("X", [
      field("a", "String"),
      enumField("r", "R"),
    ]);
    const d = datamodel([m], [{ name: "R", values: enumValues("A", "B") }]);
    const out = renderModule(d, options({ effectImportName: "Eff" }));
    expect(out).toContain('import { Schema as Eff } from "effect"');
    expect(out).toContain("Eff.Struct({");
    expect(out).toContain("Eff.String,");
    expect(out).toContain('Eff.Literal("A")');
    expect(out).toContain("Eff.Union(");
  });

  it("combines custom import name with wrappers", () => {
    const m = model("X", [
      field("a", "String", { isList: true, isRequired: false }),
    ]);
    const out = renderModule(datamodel([m]), options({ effectImportName: "Eff" }));
    expect(out).toContain("a: Eff.NullOr(Eff.Array(Eff.String)),");
  });
});